name: Frontend CI

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**', '.github/workflows/frontend.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**', '.github/workflows/frontend.yml' ]

permissions:
  pull-requests: write

jobs:
  linting-formatting-and-typecheck:
    name: Linting, Formatting & Typecheck

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install project dependencies
        run: npm run install:ci:frontend

      - name: Run formatting check
        run: npm run format:check:frontend

      - name: Run linting check
        run: npm run lint:check:frontend

      - name: Run type check
        run: npm run typecheck:frontend

  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install project dependencies
        run: npm run install:ci:frontend

      - name: Run unit tests with coverage
        run: npm run test:coverage:frontend

      - name: Report coverage (as comment on PR)
        if: always() # Report results even if tests fail
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: frontend/coverage/coverage-summary.json
          json-final-path: frontend/coverage/coverage-final.json

  e2e-tests:
    name: E2E Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install project dependencies
        run: npm run install:ci:frontend

      - name: Install Playwright browsers
        run: cd frontend && npx playwright install --with-deps

      - name: Build application
        run: npm run build:frontend

      - name: Run E2E tests
        run: npm run test:e2e:frontend

      - name: Report Playwright Results
        if: always() # Report results even if tests fail
        uses: daun/playwright-report-summary@v3
        with:
          report-file: frontend/playwright-report/results.json
